import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <header>
          <nav
            style={{
              display: "flex",
              gap: "1rem",
              padding: "1rem",
              boxShadow: "0px 2px 5px rgba(0, 0, 0, 0.1)",
            }}
          >
            <a href="/">首页</a>
            <a href="/hiragana">五十音</a>
            <a href="/vocabulary">词汇学习</a>
            <a href="/grammar">语法学习</a>
            <a href="/quizzes">测验</a>
          </nav>
        </header>
        <main style={{ padding: "2rem" }}>{children}</main>
        <footer
          style={{
            textAlign: "center",
            padding: "1rem",
            borderTop: "1px solid #ddd",
          }}
        >
          © 2024 日语学习应用
        </footer>
      </body>
    </html>
  );
}